package com.tn.GestiondeStock.exception;

public enum ErrorCodes {

	ARTICLE_NOT_FOUND(1000),
	ARTICLE_NOT_VALID(1001),
	CATEGORY_NOT_FOUND(2000),
	// Completer les suites des erreurs 
	CLIENT_NOT_FOUND(3000),
	COMMANDE_CLIENT_NOT_FOUND(4000),
	COMMANDE_FOURNISSEUR_NOT_FOUND(5000),
	ENTRPRISE_NOT_FOUND(6000),
	FOURNISSEUR_NOT_FOUND(7000),
	LIGNE_COMMANDE_CLIENT_NOT_FOUND(8000),
	LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(9000),
	LIGNE_VENTE_NOT_FOUND(10000),
	MOUVEMENTSTOCK_NOT_FOUND(11000),
	UTILISATEUR_NOT_FOUND(12000),
	VENTE_NOT_FOUND(13000)
	;
	
	private int code;
	
	ErrorCodes(int code) {
		this.code = code;
	}
	
	
	public int getCode() {
		return code;
	}
}
